baseURL = "higueronforsale.com"
disableLanguages = ["de", "it", "fr"]
disqusShortname = ""
googleAnalytics = ""
paginate = "4"
summaryLength = "30"
theme = "Higueron"
timeZone = "UTC"
title = "Higueron | For Sale"
[languages.de]
contentDir = "content/german"
copyright = "Copyright &copy; 2021 [Themefisher](https://themefisher.com). Alle Rechte vorbehalten."
languageCode = "de-DE"
languageName = "Deutsch"
weight = 3
[[languages.de.menu.main]]
hasChildren = true
name = "Mehr"
weight = 5
[languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2021 HigueronForSale.com. All Rights Reserved."
languageCode = "en-US"
languageName = "English"
weight = "1"
[[languages.en.menu.main]]
hasChildren = ""
name = "Pricing"
weight = "https://higueronforsale.com/pricing/"
[[languages.en.menu.main]]
hasChildren = ""
name = "Project"
weight = "https://higueronforsale.com/project/"
[[languages.en.menu.main]]
hasChildren = ""
name = "Contact"
weight = "https://higueronforsale.com/contact/"
[languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2021 [Themefisher](https://themefisher.com). Tous droits réservés."
languageCode = "fr-FR"
languageName = "Français"
weight = 2
[[languages.fr.menu.main]]
hasChildren = true
name = "Plus"
weight = 5
[languages.it]
contentDir = "content/italian"
copyright = "Copyright &copy; 2021 [Themefisher](https://themefisher.com). Tutti i diritti riservati."
languageCode = "it-IT"
languageName = "Italiano"
weight = 2
[[languages.it.menu.main]]
hasChildren = true
name = "Più"
weight = 5
[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
endLevel = 6
ordered = false
startLevel = 2
[[menu.footer]]
name = "Über uns"
weight = 1
[[menu.footer]]
name = "Kontakt"
weight = 11
[[menu.footer]]
name = "Häufige Fragen"
weight = 9
[[menu.footer]]
name = "Preise"
weight = 7
[[menu.footer]]
name = "Projekt"
weight = 3
[[menu.footer]]
name = "Dienstleistung"
weight = 5
[[menu.footer]]
name = "Chi siamo"
weight = 2
[[menu.footer]]
name = "Contatta"
weight = 12
[[menu.footer]]
name = "Domande frequenti"
weight = 10
[[menu.footer]]
name = "Tariffazione"
weight = 8
[[menu.footer]]
name = "Progetto"
weight = 4
[[menu.footer]]
name = "Servizio"
weight = 6
[[menu.main]]
name = "Project"
url = "https://higueronforsale.com/project/"
weight = 1
[[menu.main]]
name = "Contact"
url = "https://higueronforsale.com/contact/"
weight = 6
[[menu.main]]
name = "Pricing"
url = "https://higueronforsale.com/pricing/"
weight = 11
[[menu.main]]
name = "Startseite"
weight = 2
[[menu.main]]
name = "Über uns"
weight = 7
[[menu.main]]
name = "Kontakt"
weight = 17
[[menu.main]]
name = "Häufige Fragen"
parent = "Mehr"
weight = 12
[[menu.main]]
name = "Preise"
parent = "Mehr"
weight = 8
[[menu.main]]
name = "Projekt"
weight = 13
[[menu.main]]
name = "Dienstleistung"
parent = "Mehr"
weight = 3
[[menu.main]]
name = "Pagina iniziale"
weight = 4
[[menu.main]]
name = "Chi siamo"
weight = 9
[[menu.main]]
name = "Contatta"
weight = 18
[[menu.main]]
name = "Domande frequenti"
parent = "Più"
weight = 14
[[menu.main]]
name = "Tariffazione"
parent = "Più"
weight = 10
[[menu.main]]
name = "Progetto"
weight = 15
[[menu.main]]
name = "Servizio"
parent = "Più"
weight = 5
[[menu.main]]
identifier = "blog"
name = "Blog"
weight = 16
[module.hugoVersion]
extended = true
min = "0.87.0"
[outputs]
home = ["HTML"]
[params]
author = "Higueron For Sale"
description = "Lomas de Higueron for sale. More than 1200 New Development properties available. Building under the best construction luxury standards and a great location of Costa del Sol."
image = "images/logo.png"
logo = "images/logo.png"
logo_width = "150px"
social = []
[params.contact]
address_descriptors = false
email = "higueronforsale@gmail.com"
location = "Fuengirola, Costa del Sol"
phone = "+34 951 203 716"
[params.contact.form]
action = "#"
enable = false
success_image = "images/paper-plane.svg"
use_netlify = false
[params.cookies]
enable = true
expire_days = 2
[params.counter]
enable = true
username = ""
[params.gmap]
enable = false
gmap_api = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[[params.plugins.css]]
attributes = "media='screen'"
link = "plugins/bootstrap/css/bootstrap.min.css"
[[params.plugins.css]]
attributes = ""
link = "plugins/ionicons/css/ionicons.min.css"
[[params.plugins.css]]
attributes = ""
link = "plugins/magnific-popup/magnific-popup.min.css"
[[params.plugins.css]]
attributes = ""
link = "plugins/slick/slick.css"
[[params.plugins.js]]
attributes = ""
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
attributes = ""
link = "plugins/bootstrap/js/bootstrap.min.js"
[[params.plugins.js]]
attributes = ""
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
attributes = ""
link = "plugins/magnific-popup/magnific-popup.min.js"
[[params.plugins.js]]
attributes = ""
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
attributes = "defer"
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""
[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]
